extends RefCounted

func get_spec() -> Dictionary:
    return {
        "name": "DockingContainer",
        "backing": "PanelContainer",
        "properties": [
            {"sml":"id", "type":"identifier", "default":"—"},
            {"sml":"dockSide", "type":"enum", "default":"center"},
            {"sml":"fixedWidth", "type":"int", "default":"240"},
            {"sml":"minFixedWidth", "type":"int", "default":"140"},
            {"sml":"fixedHeight", "type":"int", "default":"—"},
            {"sml":"minFixedHeight", "type":"int", "default":"80"},
            {"sml":"heightPercent", "type":"float", "default":"50"},
            {"sml":"flex", "type":"bool", "default":"false"},
            {"sml":"closeable", "type":"bool", "default":"true"},
            {"sml":"dragToRearrangeEnabled", "type":"bool", "default":"true"},
            {"sml":"tabsRearrangeGroup", "type":"int", "default":"1"}
        ],
        "actions": [],
        "notes": [
            "Automatically creates an internal TabContainer.",
            "Direct child controls become tabs. Use the attached property syntax to define tab captions: `<containerId>.title: \"Caption\"` or `DockingContainer.title: \"Caption\"`.",
            "Attached properties are resolved by instance id first, then by type name. The qualifier must refer to the direct parent DockingContainer.",
            "dockSide supports: farLeft, farLeftBottom, left, leftBottom, center, right, rightBottom, farRight, farRightBottom.",
            "For split columns (top/bottom), height can be controlled via fixedHeight (px) or heightPercent (0..100).",
            "Priority: fixedHeight > heightPercent > automatic 50/50 fallback.",
            "Use enum syntax without quotes, e.g. dockSide: left.",
            "dragToRearrangeEnabled: false excludes this container from docking move targets (kebab menu).",
            "A container is not listed as move target for itself (same dock slot is filtered)."
        ],
        "examples_sml": [
            "DockingContainer {",
            "    id: leftDock",
            "    dockSide: left",
            "    fixedWidth: 280",
            "    dragToRearrangeEnabled: true",
            "    tabsRearrangeGroup: 1",
            "",
            "    VBoxContainer {",
            "        id: project",
            "        leftDock.title: \"Project\"",
            "    }",
            "",
            "    VBoxContainer {",
            "        id: search",
            "        leftDock.title: \"Search\"",
            "    }",
            "}",
            "",
            "// Alternatively qualify by type name:",
            "DockingContainer {",
            "    id: rightDock",
            "    dockSide: right",
            "    fixedWidth: 360",
            "",
            "    VBoxContainer {",
            "        id: inspector",
            "        DockingContainer.title: \"Inspector\"",
            "    }",
            "}",
        ]
    }
