namespace ForgeCli.Core;

internal static class ProjectScaffolder
{
    public static void Create(string projectName, string outputDirectory, bool force)
    {
        var fullPath = Path.GetFullPath(outputDirectory);
        if (Directory.Exists(fullPath) && Directory.EnumerateFileSystemEntries(fullPath).Any() && !force)
        {
            throw new InvalidOperationException($"Directory '{fullPath}' is not empty. Use --force to continue.");
        }

        Directory.CreateDirectory(fullPath);
        Directory.CreateDirectory(Path.Combine(fullPath, "assets"));

        WriteFile(fullPath, "app.sml", AppTemplate());
        WriteFile(fullPath, "main.sml", MainSmlTemplate(projectName));
        WriteFile(fullPath, "main.sms", MainSmsTemplate());
        WriteFile(fullPath, "theme.sml", ThemeTemplate());
        WriteFile(fullPath, "strings.sml", StringsTemplate(projectName));
        WriteFile(fullPath, "README.md", ReadmeTemplate(projectName));
    }

    private static void WriteFile(string root, string relativePath, string content)
    {
        var fullPath = Path.Combine(root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        File.WriteAllText(fullPath, content);
    }

    private static string AppTemplate() =>
"""
SplashScreen {
    id: splashScreen
    size: 640, 480
    duration: 500
    loadOnReady: "main.sml"

    VBoxContainer {
        anchors: left | top | right | bottom
        padding: 20, 20, 20, 20

        Control { sizeFlagsVertical: expandFill }

        Label {
            text: "Loading..."
            sizeFlagsHorizontal: shrinkCenter
        }

        Control { sizeFlagsVertical: expandFill }
    }
}
""";

    private static string MainSmlTemplate(string projectName) =>
$$"""
Window {
    id: mainWindow
    title: @Strings.windowTitle, "{{projectName}}"
    minSize: 900, 600
    size: 1200, 800

    DockingHost {
        id: mainDockHost
        anchors: left | top | right | bottom

        DockingContainer {
            id: centerDock
            dockSide: center
            flex: true
            closeable: false

            Viewport3D {
                id: viewport
                centerDock.title: "Viewport"
                anchors: left | top | right | bottom
            }
        }
    }
}
""";

    private static string MainSmsTemplate() =>
"""
fun ready() {
    log.info("Forge app ready")
}
""";

    private static string ThemeTemplate() =>
"""
Colors {
    accent: "#28A9E0"
}
""";

    private static string StringsTemplate(string projectName) =>
$$"""
Strings {
    windowTitle: "{{projectName}}"
}
""";

    private static string ReadmeTemplate(string projectName) =>
$"""
# {projectName}

Generated by ForgeCli.

## Files

- app.sml (startup splash)
- main.sml (main UI)
- main.sms (event logic)
- theme.sml (theme overrides)
- strings.sml (localized strings)

## Validate

```bash
forgecli validate --project .
```

## Generate from AI prompt

```bash
forgecli generate --project . --provider mock --prompt "create a window with docking and centered viewport3d"
```
""";
}
